#!/bin/bash
set -e

echo "Render Deployment Guide"
echo "======================="
echo ""
echo "This project is configured for deployment to Render using the 'render.yaml' blueprint."
echo "Render typically deploys automatically when changes are pushed to the branch connected in your Render service settings (e.g., main)."
echo ""
echo "Primary Deployment Method (Blueprint):"
echo "1. Create an account on Render.com."
echo "2. On the Render Dashboard, click 'New +' and then 'Blueprint'."
echo "3. Connect your GitHub repository (where this project resides)."
echo "4. Render will detect 'render.yaml' in your repository root."
echo "5. Review the services to be created (e.g., go-moon-app, go-moon-db, go-moon-redis)."
echo "6. Click 'Create New Services' (or similar button) to provision and deploy."
echo ""
echo "Manual Service Setup (Alternative, if not using Blueprint):"
echo "  If you prefer to set up services individually on Render:"
echo "  1. Web Service (for the Go App):"
echo "     - Type: Docker"
echo "     - Connect your repository."
echo "     - Dockerfile Path: ./Dockerfile"
echo "     - Health Check Path: /healthz"
echo "     - Environment Variables (set in Render UI):"
echo "       - SERVER_PORT: 8080 (Render also provides a PORT variable your app can use)"
echo "       - JWT_SECRET: Generate a strong secret in Render's UI."
echo "       - POSTGRES_DSN: Get this from your Render PostgreSQL instance's 'Internal Connection String'."
echo "       - REDIS_ADDR: Get this from your Render Redis instance's 'Internal Connection String'."
echo "  2. PostgreSQL Database:"
echo "     - Type: PostgreSQL. Create a new instance. Note its internal connection string for POSTGRES_DSN."
echo "  3. Redis:"
echo "     - Type: Redis. Create a new instance. Note its internal connection string for REDIS_ADDR."
echo ""
echo "Using Render CLI (Optional):"
echo "  Ensure you have the Render CLI installed and configured ('render login')."
echo "  You can create services from a blueprint:"
echo "    render blueprint:apply --file ./render.yaml --env-vars JWT_SECRET=$(openssl rand -hex 32) # Example to override/set a value"
echo "  Or trigger a deploy for an existing service:"
echo "    render deploy --service go-moon-app"
echo ""
echo "Local Testing of Production-like Build:"
echo "  (Assumes .env file is configured for local Docker, see .env.example)"
echo "  docker-compose build"
echo "  docker-compose up -d"
echo ""
echo "Important Notes:"
echo "  - Ensure 'render.yaml' is committed to your repository for Blueprint deployments."
echo "  - The 'repo' URL in 'render.yaml' is often a placeholder if creating blueprint from dashboard; Render uses the connected repo."
echo "  - Refer to Render's official documentation for the latest details and advanced configurations."

# This script is informational. To make it executable: chmod +x scripts/deploy.sh
# However, it doesn't perform actual deployment commands itself.
# Actual deployment to Render is git-triggered or via Render's dashboard/CLI.
exit 0
